[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "forge-std/=lib/forge-std/src/",
    "eigenlayer-contracts/=lib/eigenlayer-contracts/src/",
    "solady/=lib/solady/src/"
]

[rpc_endpoints]
holesky = "${HOLESKY_RPC_URL}"



# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
